'use client'
import type { Metadata } from "next";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const queryClient = new QueryClient()

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='flex flex-col min-h-screen'>
        <Navbar />
        <QueryClientProvider client={queryClient}>
          <main className='relative overflow-hidden flex-grow'>
                  {children}
                  <ToastContainer />
            </main>
        </QueryClientProvider>
          <Footer />
        </body>
    </html>
  );
}
